version: '3'

services:
  mysql:
    container_name: trackfit-mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Ge5cyYjWzywx2bG7
      MYSQL_DATABASE: fitness_tracker
      MYSQL_PASSWORD: Ge5cyYjWzywx2bG7
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - mysql
    restart: unless-stopped

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: Ge5cyYjWzywx2bG7
    ports:
      - "8080:80"
    networks:
      - mysql
    restart: unless-stopped

networks:
  mysql:
    driver: bridge

volumes:
  mysql:
